### PR TITLE
Fix coffee extension not changing to js

### LINKED ISSUE #3: .coffee extension remains as .coffee in Jekyll 3.1.x
I'm upgrading our site to Jekyll 3.1.x ( newtheatre/history-project#496 ) and seeing coffeescript files that compile but their extensions do not change. Two files here, lib.js is unrelated.

image

image

When omitting jekyll-coffeescript from _config.yml correct behaviour is observed.

### PR DESCRIPTION
**Pull request by wjdp**
Will close #3

### CODE REVIEW

**Comment by wjdp** [comment]
Extension would not run with `< CoffeeScript` on line 59, changing to `< Converter` fixes though I do not know why.

Running rake fails with

```
/home/will/local/jekyll-jsminify/spec/jsminify_spec.rb:3:in `<top (required)>': uninitialized constant Jekyll::Converters::CoffeeScript (NameError)
	from /var/lib/gems/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `load'
	from /var/lib/gems/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `block in load_spec_files'
	from /var/lib/gems/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `each'
	from /var/lib/gems/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `load_spec_files'
	from /var/lib/gems/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:106:in `setup'
	from /var/lib/gems/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:92:in `run'
	from /var/lib/gems/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
	from /var/lib/gems/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
	from /var/lib/gems/2.1.0/gems/rspec-core-3.4.4/exe/rspec:4:in `<main>'
/usr/bin/ruby2.1 -w -I/var/lib/gems/2.1.0/gems/rspec-core-3.4.4/lib:/var/lib/gems/2.1.0/gems/rspec-support-3.4.1/lib /var/lib/gems/2.1.0/gems/rspec-core-3.4.4/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb --color failed
```

File: lib/jekyll-jsminify.rb [hunk 1]
```diff
@@ -56,7 +56,7 @@ def convert(content)
 module Jekyll
   module Converters
     module Minify
-      class CSMinify < CoffeeScript
```
Comment (wjdp) [inline lib/jekyll-jsminify.rb]: Unsure why this was needed, may break other things

**Comment by gjtorikian** [comment]
Thanks! Will release as `0.3.0`.
